logging:
  level:
    org.hibernate.SQL: debug # logger? ?????
    org.hibernate.type.descriptor.sql: trace # ???? ? ??
spring:
  jpa:
    show-sql: true # ????? ?????
    properties:
      hibernate:
        format_sql: true # SQL ???
        highlight_sql: true # ANSI ??? ?? ????
        use_sql_comments: true # SQL ??? /* */ ?? ??

auth:
  jwt:
    issuer: sparta.com
    secret: Azqio13asxjc93zawqerAEsdD1263BDE
    accessTokenExpirationHour: 10